name: "Create release"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  validate_main_module:
    uses: jamieastley/terraform_gh_actions/.github/workflows/validate_terraform_module.yml@v1.0.0
    name: "Validate module"
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}

  validate_cloudflare_dns:
    uses: jamieastley/terraform_gh_actions/.github/workflows/validate_terraform_module.yml@v1.0.0
    name: "Validate CloudFlare DNS module"
    with:
      terraform_version: latest
      working-directory: modules/cloudflare-dns

  create_release:
    name: "Create GitHub release"
    runs-on: ubuntu-latest
    needs: [ validate_main_module, validate_cloudflare_dns ]
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
