name: "Pull Request"

on:
  pull_request:
    branches:
      - master

jobs:
  validate_main_module:
    uses: jamieastley/terraform_gh_actions/.github/workflows/validate_terraform_module.yml@v1.0.0
    name: "Validate module"
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}

  validate_cloudflare_dns:
    uses: jamieastley/terraform_gh_actions/.github/workflows/validate_terraform_module.yml@v1.0.0
    name: "Validate CloudFlare DNS module"
    with:
      terraform_version: latest
      working-directory: modules/cloudflare-dns

  output_terraform_results:
    name: "Output Terraform results"
    runs-on: ubuntu-latest
    needs: [ validate_main_module, validate_cloudflare_dns ]
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          MODULE_FMT: ${{ needs.validate_main_module.outputs.fmtOutcome }}
          MODULE_INIT: ${{ needs.validate_main_module.outputs.initOutcome }}
          MODULE_VALIDATE: ${{ needs.validate_main_module.outputs.validateOutcome }}
          MODULE_VALIDATE_OUTPUT: ${{ needs.validate_main_module.outputs.validateOutput }}
          DNS_FMT: ${{ needs.validate_oidc_provider.outputs.fmtOutcome }}
          DNS_INIT: ${{ needs.validate_oidc_provider.outputs.initOutcome }}
          DNS_VALIDATE: ${{ needs.validate_oidc_provider.outputs.validateOutcome }}
          DNS_VALIDATE_OUTPUT: ${{ needs.validate_oidc_provider.outputs.validateOutput }}

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const title = 'Terraform Results'
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes(title)
            })

            // 2. Prepare format of the comment
            const output = `## ${title}

            ### Module
            #### Terraform fmt 🖌\`${{ env.MODULE_FMT }}\`
            #### Terraform init ⚙️\`${{ env.MODULE_INIT }}\`
            #### Terraform validate 🤖\`${{ env.MODULE_VALIDATE }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ env.MODULE_VALIDATE_OUTPUT }}
            \`\`\`

            </details>

            ### Submodule - CloudFlare DNS
            #### Terraform fmt 🖌\`${{ env.DNS_FMT }}\`
            #### Terraform init ⚙️\`${{ env.DNS_INIT }}\`
            #### Terraform validate 🤖\`${{ env.DNS_VALIDATE }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ env.DNS_VALIDATE_OUTPUT }}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }