name: "Pull Request"

on:
  pull_request:

jobs:
  pull_request:
    name: "Pull Request"
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: example
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - uses: dangoslen/changelog-enforcer@v3